apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ntfy.labels" . | nindent 4 }}
data:
  server.yml: |

    log-level: {{ .Values.logLevel }}
    log-format: {{ .Values.logFormat }}
    log-file: /dev/stdout
    base-url: https://{{ .Values.host }}

    cache-file: {{ .Values.cacheFile }}
    cache-duration: "{{ .Values.cacheDuration }}"

    attachment-cache-dir: {{ .Values.attachmentCacheDir }}
    attachment-total-size-limit: "{{ .Values.attachmentTotalSizeLimit }}"
    attachment-file-size-limit: "{{ .Values.attachmentFileSizeLimit }}"
    attachment-expiry-duration: "{{ .Values.attachmentExpiryDuration }}"

    auth-file: {{ .Values.authFile }}
    auth-default-access: {{ .Values.authDefaultAccess }}

    global-topic-limit: {{ .Values.globalTopicLimit }}
    visitor-subscription-limit: {{ .Values.visitorSubscriptionLimit }}
    visitor-request-limit-burst: {{ .Values.visitorRequestLimitBurst }}
    visitor-request-limit-replenish: "{{ .Values.visitorRequestLimitReplenish }}"
    visitor-request-limit-exempt-hosts: "{{ .Values.visitorRequestLimitExemptHosts }}"
    visitor-message-daily-limit: {{ .Values.visitorMessageDailyLimit }}

    behind-proxy: {{ .Values.behindProxy }}

    {{- if .Values.metrics.enabled }}
    enable-metrics: true
    metrics-listen-http: ":9090"
    {{- end }}
