{{- if .Values.metrics.enabled -}}
apiVersion: v1
kind: Service
metadata:
{{- if .Values.metrics.service.annotations }}
  annotations: {{ toYaml .Values.metrics.service.annotations | nindent 4 }}
{{- end }}
  labels:
    {{- include "ntfy.labels" . | nindent 4 }}
  {{- if .Values.metrics.service.labels }}
    {{- toYaml .Values.metrics.service.labels | nindent 4 }}
  {{- end }}
  name: {{ include "ntfy.fullname" . }}-metrics
spec:
  type: {{ .Values.metrics.service.type }}
  ports:
    - name: {{ .Values.metrics.portName }}
      port: {{ .Values.metrics.port }}
      protocol: TCP
      targetPort: 9090
  selector:
    {{- include "ntfy.selectorLabels" . | nindent 4 }}
{{- end }}

---

{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ntfy.fullname" . }}
{{- if .Values.metrics.serviceMonitor.namespace }}
  namespace: {{ .Values.metrics.serviceMonitor.namespace }}
{{- else }}
  namespace: {{ .Release.Namespace }}
{{- end }}
  labels:
    {{- include "ntfy.labels" . | nindent 4 }}
  {{- if .Values.metrics.serviceMonitor.additionalLabels }}
    {{- toYaml .Values.metrics.serviceMonitor.additionalLabels | nindent 4 }}
  {{- end }}
  {{- if .Values.metrics.serviceMonitor.annotations }}
  annotations: {{ toYaml .Values.metrics.serviceMonitor.annotations | nindent 4 }}
  {{- end }}
spec:
  endpoints:
    - port: {{ .Values.metrics.portName }}
      interval: {{ .Values.metrics.serviceMonitor.scrapeInterval }}
    {{- if .Values.metrics.serviceMonitor.honorLabels }}
      honorLabels: true
    {{- end }}
    {{- if .Values.metrics.serviceMonitor.relabelings }}
      relabelings: {{ toYaml .Values.metrics.serviceMonitor.relabelings | nindent 8 }}
    {{- end }}
    {{- if .Values.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings: {{ toYaml .Values.metrics.serviceMonitor.metricRelabelings | nindent 8 }}
    {{- end }}
{{- if .Values.metrics.serviceMonitor.jobLabel }}
  jobLabel: {{ .Values.metrics.serviceMonitor.jobLabel | quote }}
{{- end }}
{{- if .Values.metrics.serviceMonitor.namespaceSelector }}
  namespaceSelector: {{ toYaml .Values.metrics.serviceMonitor.namespaceSelector | nindent 4 }}
{{- else }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
{{- if .Values.metrics.serviceMonitor.targetLabels }}
  targetLabels:
  {{- range .Values.metrics.serviceMonitor.targetLabels }}
    - {{ . }}
  {{- end }}
{{- end }}
  selector:
    matchLabels:
      {{- include "ntfy.selectorLabels" . | nindent 6 }}
{{- end }}
