
{{ if .Values.ingress.enabled }}
{{- range .Values.ingress.tls }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .secretName }}
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .email }}
    privateKeySecretRef:
      name: {{ .secretName }}
    solvers:
    - http01:
        ingress:
          class: nginx
{{- end }}
{{- end }}